name = "cloudflare-saas-stack"
compatibility_date = "2024-09-03"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "SaveChat-db"
database_id = "d23dbd7a-a0a4-41ef-9c75-4911e88313cb"
migrations_dir = "./drizzle"
